project:
  type: website
  output-dir: docs

website:
  title: "Matthaios Letsios"
  navbar:
    left:
      - href: ml_and_stats.qmd
        text: ML and Stats
format:
  html:
    theme: cosmo
    css: styles.css